-- MySQL Script generated by MySQL Workbench
-- Fri Jul 14 01:53:24 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema edstyles
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `edstyles` ;

-- -----------------------------------------------------
-- Schema edstyles
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `edstyles` DEFAULT CHARACTER SET utf8mb4 ;
USE `edstyles` ;

-- -----------------------------------------------------
-- Table `edstyles`.`articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edstyles`.`articles` ;

CREATE TABLE IF NOT EXISTS `edstyles`.`articles` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `price` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  `image` VARCHAR(255) NOT NULL DEFAULT 'http://via.placeholder.com/532x630',
  `paypal` VARCHAR(60) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edstyles`.`sizes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edstyles`.`sizes` ;

CREATE TABLE IF NOT EXISTS `edstyles`.`sizes` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edstyles`.`article_size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edstyles`.`article_size` ;

CREATE TABLE IF NOT EXISTS `edstyles`.`article_size` (
  `article_id` INT(11) UNSIGNED NOT NULL,
  `size_id` INT(11) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `edstyles`.`articles`
-- -----------------------------------------------------
START TRANSACTION;
USE `edstyles`;
INSERT INTO `edstyles`.`articles` (`id`, `name`, `description`, `price`, `image`, `paypal`, `created_at`, `updated_at`) VALUES (NULL, 'Camiseta ED clásica', 'Now that there is the Tec-9, a crappy spray gun from South Miami. This gun is advertised as the most popular gun in American crime. Do you believe that shit? It actually says that in the little book that comes with it: the most popular gun in American crime. Like they\'re actually proud of that shit. ', 1200, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `edstyles`.`sizes`
-- -----------------------------------------------------
START TRANSACTION;
USE `edstyles`;
INSERT INTO `edstyles`.`sizes` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Small', DEFAULT, DEFAULT);
INSERT INTO `edstyles`.`sizes` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Medium', DEFAULT, DEFAULT);
INSERT INTO `edstyles`.`sizes` (`id`, `name`, `created_at`, `updated_at`) VALUES (NULL, 'Large', DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `edstyles`.`article_size`
-- -----------------------------------------------------
START TRANSACTION;
USE `edstyles`;
INSERT INTO `edstyles`.`article_size` (`article_id`, `size_id`, `created_at`, `updated_at`) VALUES (1, 1, DEFAULT, DEFAULT);
INSERT INTO `edstyles`.`article_size` (`article_id`, `size_id`, `created_at`, `updated_at`) VALUES (1, 2, DEFAULT, DEFAULT);
INSERT INTO `edstyles`.`article_size` (`article_id`, `size_id`, `created_at`, `updated_at`) VALUES (1, 3, DEFAULT, DEFAULT);

COMMIT;

